final List<Map<String, dynamic>> imageList = [
  {
    "url": "https://picsum.photos/100",
    "name": "Anime",
    "items": 21,
    "id": 0,
  },
  {
    "url": "https://picsum.photos/200",
    "name": "Dogs",
    "items": 54,
    "id": 1,
  },
  {
    "url": "https://picsum.photos/50",
    "name": "Songs",
    "items": 3,
    "id": 2,
  },
  {
    "url": "https://picsum.photos/70",
    "name": "Pokemon",
    "items": 12,
    "id": 3,
  },
  {
    "url": "https://picsum.photos/90",
    "name": "Anime",
    "items": 21,
    "id": 4,
  },
  {
    "url": "https://picsum.photos/80",
    "name": "Dogs",
    "items": 54,
    "id": 5,
  },
  {
    "url": "https://picsum.photos/120",
    "name": "Songs",
    "items": 3,
    "id": 6,
  },
  {
    "url": "https://picsum.photos/110",
    "name": "Pokemon",
    "items": 12,
    "id": 7,
  },
  {
    "url": "https://picsum.photos/105",
    "name": "Anime",
    "items": 21,
    "id": 8,
  },
  {
    "url": "https://picsum.photos/85",
    "name": "Dogs",
    "items": 54,
    "id": 9,
  },
  {
    "url": "https://picsum.photos/109",
    "name": "Anime",
    "items": 21,
    "id": 10,
  },
  {
    "url": "https://picsum.photos/107",
    "name": "Dogs",
    "items": 54,
    "id": 11,
  },
  {
    "url": "https://picsum.photos/106",
    "name": "Songs",
    "items": 3,
    "id": 12,
  },
  {
    "url": "https://picsum.photos/104",
    "name": "Pokemon",
    "items": 12,
    "id": 13,
  },
  {
    "url": "https://picsum.photos/103",
    "name": "Anime",
    "items": 21,
    "id": 14,
  },
  {
    "url": "https://picsum.photos/102",
    "name": "Dogs",
    "items": 54,
    "id": 15,
  },
  {
    "url": "https://picsum.photos/101",
    "name": "Songs",
    "items": 3,
    "id": 16,
  },
  {
    "url": "https://picsum.photos/112",
    "name": "Pokemon",
    "items": 12,
    "id": 17,
  },
  {
    "url": "https://picsum.photos/60",
    "name": "Songs",
    "items": 3,
    "id": 18,
  },
  {
    "url": "https://picsum.photos/108",
    "name": "Pokemon",
    "items": 12,
    "id": 19
  },
];
