// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_key_and_iv`, `get_crypto_params`
// These types are ignored because they are not used by any `pub` functions: `CRYPTO_PARAMS`, `CryptoParams`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`, `zeroize`

Future<Uint8List> encryptData({required List<int> data}) =>
    RustLib.instance.api.crateApiEncryptionEncryptData(data: data);

Future<Uint8List> decryptData({required List<int> encryptedData}) =>
    RustLib.instance.api
        .crateApiEncryptionDecryptData(encryptedData: encryptedData);

Future<bool> setCryptoParams({required String password}) =>
    RustLib.instance.api.crateApiEncryptionSetCryptoParams(password: password);
