// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> setPassword({required String password}) =>
    RustLib.instance.api.crateApiFileSetPassword(password: password);

Future<void> createDir({required String dir, required String albumName}) =>
    RustLib.instance.api.crateApiFileCreateDir(dir: dir, albumName: albumName);

Future<List<String>> getDirs({required String dir}) =>
    RustLib.instance.api.crateApiFileGetDirs(dir: dir);

Future<Map<String, (String, double)>> getImages({required String dir}) =>
    RustLib.instance.api.crateApiFileGetImages(dir: dir);

Future<Map<String, (String, double)>?> getAlbumThumb({required String dir}) =>
    RustLib.instance.api.crateApiFileGetAlbumThumb(dir: dir);

Future<Uint8List> getFileThumb({required String path}) =>
    RustLib.instance.api.crateApiFileGetFileThumb(path: path);

Future<Uint8List> getFile({required String path}) =>
    RustLib.instance.api.crateApiFileGetFile(path: path);

Future<void> saveFile({required List<int> imageData, required String dir}) =>
    RustLib.instance.api.crateApiFileSaveFile(imageData: imageData, dir: dir);
